name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Print Node.js version
        run: node -v

      - name: Install dependencies
        run: npm install

      - name: Set Firebase environment variables
        run: |
          echo "export const firebaseConfig = {
            apiKey: '${{ secrets.VITE_REACT_APP_FIREBASE_API_KEY }}',
            authDomain: '${{ secrets.VITE_REACT_APP_FIREBASE_AUTH_DOMAIN }}',
            projectId: '${{ secrets.VITE_REACT_APP_FIREBASE_PROJECT_ID }}',
            storageBucket: '${{ secrets.VITE_REACT_APP_FIREBASE_STORAGE_BUCKET }}',
            messagingSenderId: '${{ secrets.VITE_REACT_APP_FIREBASE_MESSAGING_SENDER_ID }}',
            appId: '${{ secrets.VITE_REACT_APP_FIREBASE_APP_ID }}'
          };" > src/firebaseConfig.js

      - name: Build project
        run: npm run build
        env:
          VITE_REACT_APP_FIREBASE_API_KEY: ${{ secrets.VITE_REACT_APP_FIREBASE_API_KEY }}
          VITE_REACT_APP_FIREBASE_APP_ID: ${{ secrets.VITE_REACT_APP_FIREBASE_APP_ID }}
          VITE_REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_REACT_APP_FIREBASE_AUTH_DOMAIN }}
          VITE_REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_REACT_APP_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_REACT_APP_FIREBASE_PROJECT_ID: ${{ secrets.VITE_REACT_APP_FIREBASE_PROJECT_ID }}
          VITE_REACT_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_REACT_APP_FIREBASE_STORAGE_BUCKET }}

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    environment: Deploy
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
