name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
        env:
          VITE_REACT_APP_FIREBASE_API_KEY: AIzaSyCY-B7aHW4rRccwMTZJmIQu628D1Rfr_nM
          VITE_REACT_APP_FIREBASE_APP_ID: 1:867199092595:web:14a290118200fa185c2706
          VITE_REACT_APP_FIREBASE_AUTH_DOMAIN: move-software.firebaseapp.com
          VITE_REACT_APP_FIREBASE_MESSAGING_SENDER_ID: 867199092595
          VITE_REACT_APP_FIREBASE_PROJECT_ID: move-software
          VITE_REACT_APP_FIREBASE_STORAGE_BUCKET: move-software.appspot.com

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    environment: Deploy
    if: github.ref == 'refs/heads/main'

    env:
      VITE_REACT_APP_FIREBASE_API_KEY: AIzaSyCY-B7aHW4rRccwMTZJmIQu628D1Rfr_nM
      VITE_REACT_APP_FIREBASE_APP_ID: 1:867199092595:web:14a290118200fa185c2706
      VITE_REACT_APP_FIREBASE_AUTH_DOMAIN: move-software.firebaseapp.com
      VITE_REACT_APP_FIREBASE_MESSAGING_SENDER_ID: 867199092595
      VITE_REACT_APP_FIREBASE_PROJECT_ID: move-software
      VITE_REACT_APP_FIREBASE_STORAGE_BUCKET: move-software.appspot.com

    steps:
      - name: Check Secrets
        run: |
          echo "API Key: ${{ secrets.VITE_REACT_APP_FIREBASE_API_KEY }}"

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
